"""Shared dataset and formatting helpers for Lightning training pipelines."""

from __future__ import annotations

from dataclasses import asdict
import json
import random
from typing import Any, Callable, Optional

from datasets import Dataset, DatasetDict, concatenate_datasets, load_dataset
from lightning import LightningDataModule
from torch.utils.data import DataLoader

from lightning_grpo.utils.configs.base import DataConfig, DatasetSource, ModelConfig


class ConversationTemplate:
    """Convert row-based samples into chat-style message lists."""

    def __init__(
        self,
        prompt_column: str,
        response_column: str,
        messages_column: str = "messages",
        system_prompt: Optional[str] = None,
    ) -> None:
        self.prompt_column = prompt_column
        self.response_column = response_column
        self.messages_column = messages_column
        self.system_prompt = system_prompt

    def __call__(self, sample: dict[str, Any]) -> dict[str, Any]:
        """Create a canonical message list for one sample."""

        if self.messages_column in sample and sample[self.messages_column] is not None:
            return {"messages": sample[self.messages_column]}
        if "conversations" in sample and sample["conversations"] is not None:
            return {"messages": sample["conversations"]}

        messages: list[dict[str, str]] = []
        if self.system_prompt:
            messages.append({"role": "system", "content": self.system_prompt})

        if self.prompt_column not in sample:
            raise KeyError(f"Prompt column '{self.prompt_column}' not found in sample.")

        messages.append({"role": "user", "content": str(sample[self.prompt_column])})
        if self.response_column in sample and sample[self.response_column] is not None:
            messages.append({"role": "assistant", "content": str(sample[self.response_column])})
        return {"messages": messages}


SYSTEM_PROMPTS = [
    "你是一个知识丰富的AI，尽力为用户提供准确的信息。",
    "你是minimind，一个小巧但有用的语言模型。",
    "你是一个专业的AI助手，请提供有价值的回答。",
    "你是minimind，请尽力帮助用户解决问题。",
    "你是一个可靠的AI，请给出准确的回答。",
    "You are a helpful AI assistant.",
    "You are minimind, a lightweight intelligent assistant.",
    "You are a friendly chatbot. Please answer the user's questions carefully.",
    "You are a knowledgeable AI. Try your best to provide accurate information.",
    "You are minimind, a small but useful language model.",
]


def preprocess_chat_messages(
    messages: list[dict[str, Any]],
    add_system_ratio: float = 0.0,
) -> list[dict[str, Any]]:
    """Normalize chat messages while preserving tool-use samples."""

    normalized = [dict(message) for message in messages]
    if any(message.get("tools") for message in normalized):
        return normalized

    if normalized and normalized[0].get("role") != "system" and add_system_ratio > 0.0:
        if random.random() < add_system_ratio:
            normalized = [{"role": "system", "content": random.choice(SYSTEM_PROMPTS)}] + normalized
    return normalized


def postprocess_chat_text(text: str, empty_think_ratio: float = 1.0) -> str:
    """Optionally remove empty think tags generated by the chat template."""

    needle = "<think>\n\n</think>\n\n"
    if needle in text and random.random() > empty_think_ratio:
        return text.replace(needle, "")
    return text


def normalize_conversation_messages(messages: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], Any]:
    """Normalize message fields and extract tool definitions from system prompts."""

    normalized: list[dict[str, Any]] = []
    tools = None
    for message in messages:
        current = dict(message)
        if current.get("role") == "system" and current.get("tools"):
            tools = json.loads(current["tools"]) if isinstance(current["tools"], str) else current["tools"]
        if current.get("tool_calls") and isinstance(current["tool_calls"], str):
            current["tool_calls"] = json.loads(current["tool_calls"])
        normalized.append(current)
    return normalized, tools


DEFAULT_VAL_SPLIT_NAME = "test"


def _load_single_dataset(source: DatasetSource, seed: int, cache_dir: str) -> Dataset:
    """Load one dataset source from the Hugging Face hub."""

    dataset = load_dataset(
        source.path,
        source.config_name,
        split=source.split,
        cache_dir=cache_dir,
    )
    if source.columns:
        dataset = dataset.select_columns(source.columns)
    if source.weight < 1.0:
        sample_size = max(1, int(len(dataset) * source.weight))
        dataset = dataset.shuffle(seed=seed).select(range(sample_size))
    return dataset


def _load_local_json_datasets(files: list[str], cache_dir: str) -> Dataset:
    """Load one or more local JSON/JSONL files as a single training split."""

    datasets = [load_dataset("json", data_files=path, split="train", cache_dir=cache_dir) for path in files]
    return concatenate_datasets(datasets) if len(datasets) > 1 else datasets[0]


def resolve_validation_split_name(data_config: DataConfig, dataset_dict: DatasetDict) -> Optional[str]:
    """Resolve which validation split should be used for the current dataset config."""

    if data_config.val_split and data_config.val_split in dataset_dict:
        return data_config.val_split
    if DEFAULT_VAL_SPLIT_NAME in dataset_dict:
        return DEFAULT_VAL_SPLIT_NAME
    return None


def load_dataset_from_config(data_config: DataConfig) -> DatasetDict:
    """Load a dataset or dataset mixture from configuration."""

    def _shuffle_dataset(dataset: Dataset) -> Dataset:
        shuffle_kwargs = {"seed": data_config.split_seed}
        if data_config.streaming:
            shuffle_kwargs["buffer_size"] = data_config.shuffle_buffer_size
        return dataset.shuffle(**shuffle_kwargs)

    if data_config.train_files:
        dataset_dict = DatasetDict({
            data_config.train_split: _load_local_json_datasets(data_config.train_files, data_config.cache_dir)
        })
        if data_config.val_files:
            val_split_name = data_config.val_split or DEFAULT_VAL_SPLIT_NAME
            dataset_dict[val_split_name] = _load_local_json_datasets(data_config.val_files, data_config.cache_dir)
    elif data_config.dataset_mixture:
        datasets = [
            _load_single_dataset(source, seed=data_config.split_seed, cache_dir=data_config.cache_dir)
            for source in data_config.dataset_mixture
        ]
        combined_dataset = _shuffle_dataset(concatenate_datasets(datasets))
        dataset_dict = DatasetDict({data_config.train_split: combined_dataset})
    elif data_config.dataset_name:
        dataset_dict = load_dataset(
            data_config.dataset_name,
            data_config.dataset_config,
            cache_dir=data_config.cache_dir,
        )
        if data_config.streaming and data_config.train_split in dataset_dict:
            dataset_dict[data_config.train_split] = _shuffle_dataset(dataset_dict[data_config.train_split])
    else:
        raise ValueError("One of data.train_files, data.dataset_name, or data.dataset_mixture must be configured.")

    return dataset_dict


def map_dataset_with_config(
    dataset: Dataset,
    preprocess_fn: Callable[[dict[str, list[Any]]], dict[str, list[Any]]],
    data_config: DataConfig,
    desc: str,
) -> Dataset:
    """Apply a batched dataset transform using shared preprocessing settings."""

    return dataset.map(
        preprocess_fn,
        batched=True,
        batch_size=data_config.preprocessing_batch_size,
        num_proc=None if data_config.streaming else data_config.num_workers,
        remove_columns=list(dataset.column_names),
        load_from_cache_file=data_config.preprocessing_use_cache,
        keep_in_memory=data_config.preprocessing_keep_in_memory,
        desc=desc,
    )


def apply_chat_template(
    tokenizer: Any,
    messages: list[dict[str, str]],
    add_generation_prompt: bool = False,
    tools: Any = None,
    return_assistant_tokens_mask: bool = False,
    **chat_template_kwargs: Any,
) -> str:
    """Render messages into a training string with the tokenizer template."""

    if tokenizer.chat_template is None:
        rendered = []
        for message in messages:
            rendered.append(f"<{message['role']}>\n{message['content']}")
        if add_generation_prompt:
            rendered.append("<assistant>\n")
        return "\n".join(rendered)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=add_generation_prompt,
        tools=tools,
        return_assistant_tokens_mask=return_assistant_tokens_mask,
        **chat_template_kwargs,
    )


def dump_data_config(data_config: DataConfig) -> dict[str, Any]:
    """Serialize the data configuration for logging and checkpoint metadata."""

    return asdict(data_config)


class BaseDataModule(LightningDataModule):
    """Reusable base class for dataset-driven Lightning data modules."""

    def __init__(self, data_config: DataConfig) -> None:
        super().__init__()
        self.data_config = data_config
        self.train_dataset: Optional[Dataset] = None
        self.val_dataset: Optional[Dataset] = None

    def load_dataset_dict(self) -> DatasetDict:
        """Load the configured dataset dictionary."""

        return load_dataset_from_config(self.data_config)

    def resolve_val_split_name(self, dataset_dict: DatasetDict) -> Optional[str]:
        """Resolve the validation split name for the current dataset dictionary."""

        return resolve_validation_split_name(self.data_config, dataset_dict)

    def map_dataset(
        self,
        dataset: Dataset,
        preprocess_fn: Callable[[dict[str, list[Any]]], dict[str, list[Any]]],
        desc: str,
    ) -> Dataset:
        """Apply a shared batched dataset preprocessing transform."""

        return map_dataset_with_config(dataset, preprocess_fn, self.data_config, desc)

    def _build_dataloader(
        self,
        dataset: Dataset,
        batch_size: int,
        collate_fn: Callable[[list[dict[str, Any]]], Any],
        *,
        shuffle: bool,
        drop_last: bool,
    ) -> DataLoader:
        """Build a dataloader with shared worker and memory settings."""

        return DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=self.data_config.num_workers,
            collate_fn=collate_fn,
            pin_memory=True,
            drop_last=drop_last,
        )


class BaseLMDataModule(BaseDataModule):
    """Common utilities for language-model training pipelines."""

    def __init__(self, data_config: DataConfig, model_config: ModelConfig) -> None:
        super().__init__(data_config)
        self.model_config = model_config


class ChatTemplateDataModule(BaseLMDataModule):
    """Base class for chat-style pipelines backed by `ConversationTemplate`."""

    def __init__(
        self,
        data_config: DataConfig,
        model_config: ModelConfig,
        system_prompt: Optional[str] = None,
    ) -> None:
        super().__init__(data_config, model_config)
        self.system_prompt = system_prompt

    def build_conversation_template(self) -> ConversationTemplate:
        """Construct the row-to-messages formatter from chat data settings."""

        prompt_column = getattr(self.data_config, "prompt_column")
        response_column = getattr(self.data_config, "response_column")
        messages_column = getattr(self.data_config, "messages_column", "messages")
        return ConversationTemplate(
            prompt_column=prompt_column,
            response_column=response_column,
            messages_column=messages_column,
            system_prompt=self.system_prompt,
        )

    @staticmethod
    def iter_batch_samples(batch: dict[str, list[Any]]) -> list[dict[str, Any]]:
        """Convert a dict-of-lists batch into a list of row dictionaries."""

        batch_size = len(next(iter(batch.values())))
        return [
            {key: value[index] for key, value in batch.items()}
            for index in range(batch_size)
        ]
